# Generated by Django 5.0.3 on 2024-03-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(help_text='12 digit P-ID', max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('portfolio_availability', models.BooleanField(default=False)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
